// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGeFznwFfmIdI4uLV2gfqTWVBx-ZMW0lg',
    appId: '1:464857061623:web:40d74e8111583f08b85bf2',
    messagingSenderId: '464857061623',
    projectId: 'pasahero-db',
    authDomain: 'pasahero-db.firebaseapp.com',
    storageBucket: 'pasahero-db.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVARrqYFWIy3i7wajAqKZP3ZqmfYG7sL0',
    appId: '1:464857061623:android:10d97a90c6aca517b85bf2',
    messagingSenderId: '464857061623',
    projectId: 'pasahero-db',
    storageBucket: 'pasahero-db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcxn_LYdvK6CJ9oM79FKRWk3iRlphB1Ts',
    appId: '1:464857061623:ios:6107ed673c96dd72b85bf2',
    messagingSenderId: '464857061623',
    projectId: 'pasahero-db',
    storageBucket: 'pasahero-db.firebasestorage.app',
    androidClientId: '464857061623-43gdtivbg77t98g0t1vsti1c6hb5hc96.apps.googleusercontent.com',
    iosClientId: '464857061623-20ttrk6fp3bo9os1um434lr1g5vv8tsd.apps.googleusercontent.com',
    iosBundleId: 'com.pasahero.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcxn_LYdvK6CJ9oM79FKRWk3iRlphB1Ts',
    appId: '1:464857061623:ios:6107ed673c96dd72b85bf2',
    messagingSenderId: '464857061623',
    projectId: 'pasahero-db',
    storageBucket: 'pasahero-db.firebasestorage.app',
    androidClientId: '464857061623-43gdtivbg77t98g0t1vsti1c6hb5hc96.apps.googleusercontent.com',
    iosClientId: '464857061623-20ttrk6fp3bo9os1um434lr1g5vv8tsd.apps.googleusercontent.com',
    iosBundleId: 'com.pasahero.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGeFznwFfmIdI4uLV2gfqTWVBx-ZMW0lg',
    appId: '1:464857061623:web:6a99bd738814bc2ab85bf2',
    messagingSenderId: '464857061623',
    projectId: 'pasahero-db',
    authDomain: 'pasahero-db.firebaseapp.com',
    storageBucket: 'pasahero-db.firebasestorage.app',
  );

}