// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg1ToWpDGw2rd0nDs1NDlcBF40tt68OOs',
    appId: '1:66461159713:web:c20c140439a1ede58dee60',
    messagingSenderId: '66461159713',
    projectId: 'pasahero-78208',
    authDomain: 'pasahero-78208.firebaseapp.com',
    storageBucket: 'pasahero-78208.firebasestorage.app',
    measurementId: 'G-L9ZG9TJZ85',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIYNAjmOZOSY558KqbtrF6nGF6hi_6CKE',
    appId: '1:66461159713:android:4204216d4cf64fb68dee60',
    messagingSenderId: '66461159713',
    projectId: 'pasahero-78208',
    storageBucket: 'pasahero-78208.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlSYC-50LvbPLSMN9qDujf4Nhpk5fwSp4',
    appId: '1:66461159713:ios:abb26bb7cdb715d08dee60',
    messagingSenderId: '66461159713',
    projectId: 'pasahero-78208',
    storageBucket: 'pasahero-78208.firebasestorage.app',
    iosClientId: '66461159713-ici81fh4d7pgkb7588mjg323rp7353gu.apps.googleusercontent.com',
    iosBundleId: 'com.example.user',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlSYC-50LvbPLSMN9qDujf4Nhpk5fwSp4',
    appId: '1:66461159713:ios:abb26bb7cdb715d08dee60',
    messagingSenderId: '66461159713',
    projectId: 'pasahero-78208',
    storageBucket: 'pasahero-78208.firebasestorage.app',
    iosClientId: '66461159713-ici81fh4d7pgkb7588mjg323rp7353gu.apps.googleusercontent.com',
    iosBundleId: 'com.example.user',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCg1ToWpDGw2rd0nDs1NDlcBF40tt68OOs',
    appId: '1:66461159713:web:f2ff62dc6c73aaa88dee60',
    messagingSenderId: '66461159713',
    projectId: 'pasahero-78208',
    authDomain: 'pasahero-78208.firebaseapp.com',
    storageBucket: 'pasahero-78208.firebasestorage.app',
    measurementId: 'G-82T1SWYYBN',
  );
}
